import { systems, systemById } from "./data/systems.js";
import { posts, postById } from "./data/blog.js";
import { listings, trustLevels, communitySchema } from "./data/community.js";
import { shell, icon, badge, cards, sources } from "./components.js";
import { topicById } from "./data/learn.js";

const systemCard = system => `<article class="system-card system-card--${system.license.tone}">${icon(system.icon)}${badge(system.license.status,system.license.tone)}<p class="eyebrow">${system.edition}</p><h2>${system.name}</h2><p>${system.hook}</p><a href="#/system/${system.id}">Learn this system <span aria-hidden="true">→</span></a></article>`;

export const homeView = () => shell(`<section class="hero ember-hero"><div><p class="eyebrow">Ember & Stone · Learn D&D from start to finish</p><h1>Everything D&D. <em>Made easier to learn.</em></h1><p class="hero-copy">Start with zero knowledge or jump straight to the rule you need. Learn in bite-sized pages, watch the matching lesson, roll the dice live, practice in Iron Pit, then use it in a real Hearthford adventure.</p><div class="hero-actions"><a class="button" href="#/learn/play">I want to play</a><a class="button button--ghost" href="#/learn/dm">I want to DM</a></div></div><aside><strong>ONE SIMPLE IDEA</strong><p>The d20 usually answers <em>did it work?</em> The other dice often answer <em>how much happened?</em> We build outward from there.</p></aside></section>
<section class="section"><header><p class="eyebrow">Pick one thing</p><h2>Learn D&D in small pieces.</h2><p>No giant rulebook wall. Every page gives the quick answer first, then deeper detail when you want it.</p></header><div class="lesson-grid gateway-grid">
<a class="lesson-card gateway-card" href="#/learn/terminology"><span>00</span><h3>Terminology</h3><p>DM, PC, NPC, DC, AC, proficiency, HP, RAW, concentration, and the words people throw around at the table.</p></a>
<a class="lesson-card gateway-card" href="#/learn/play"><span>01</span><h3>Play D&D</h3><p>Terminology, character sheets, checks, roleplay, combat, and your first session.</p></a>
<a class="lesson-card gateway-card" href="#/learn/dm"><span>02</span><h3>DM D&D</h3><p>Run scenes, set DCs, use monsters, pace adventures, and adjudicate the game.</p></a>
<a class="lesson-card gateway-card" href="#/learn/dice"><span>03</span><h3>Dice</h3><p>See the dice roll. Learn d4 through d20, notation, modifiers, advantage, and probability.</p></a>
<a class="lesson-card gateway-card" href="#/learn/saves"><span>04</span><h3>Saving Throws</h3><p>Watch live pass/fail examples for all six saving throws.</p></a>
<a class="lesson-card gateway-card" href="#/learn/combat"><span>05</span><h3>Combat</h3><p>Initiative, turns, actions, attack rolls, AC, damage, movement, and reactions.</p></a>
<a class="lesson-card gateway-card" href="#/learn/damage"><span>06</span><h3>Damage Types</h3><p>Every damage type, what it means, and the kinds of monsters/effects that commonly use it.</p></a>
<a class="lesson-card gateway-card" href="#/learn/characters"><span>07</span><h3>Characters</h3><p>Build directly on an interactive teaching character sheet.</p></a>
<a class="lesson-card gateway-card" href="#/learn/monsters"><span>08</span><h3>Monsters</h3><p>Read stat blocks, understand monster families, defenses, and tactics.</p></a>
<a class="lesson-card gateway-card" href="#/learn/magic"><span>09</span><h3>Magic</h3><p>Spell attacks, saves, slots, concentration, duration, targeting, and advanced magic.</p></a>
</div></section>`);

export const learnView = id => {
  const topic=topicById(id); if(!topic) return notFoundView();
  const chunks=(topic.chunks||[]).map(([title,text],index)=>`<article class="lesson-card"><span>${String(index+1).padStart(2,"0")}</span><h3>${title}</h3><p>${text}</p></article>`).join("");
  const damage=(topic.damageTypes||[]).map(([type,users,meaning])=>`<article class="damage-card"><h3>${type}</h3><p><strong>Common examples:</strong> ${users}</p><p>${meaning}</p></article>`).join("");
  const interactive = id==="dice" ? `<section class="interactive-lab"><h2>Roll a die</h2><p>Pick a die and watch the result. The notation tells you how many dice and how many sides.</p><div class="roll-controls"><select id="die-select" aria-label="Choose a die"><option value="4">d4</option><option value="6">d6</option><option value="8">d8</option><option value="10">d10</option><option value="12">d12</option><option value="20" selected>d20</option><option value="100">d100</option></select><button class="button" id="roll-die">Roll</button></div><div class="roll-stage" aria-live="polite"><div class="visual-die" id="visual-die">d20</div><strong id="roll-result">Ready</strong><p id="roll-explain">d20 = roll one twenty-sided die.</p></div></section>`
  : id==="saves" ? `<section class="interactive-lab"><h2>Live saving throw</h2><p>Something is happening to your character. Roll the d20, add the save modifier, and compare the total to the DC.</p><div class="roll-controls"><label>Save<select id="save-type"><option>Strength</option><option selected>Dexterity</option><option>Constitution</option><option>Intelligence</option><option>Wisdom</option><option>Charisma</option></select></label><label>Modifier<input id="save-mod" type="number" value="3"></label><label>DC<input id="save-dc" type="number" value="14"></label><button class="button" id="roll-save">Roll save</button><button class="button button--ghost" id="show-save-pass">Show a pass</button><button class="button button--ghost" id="show-save-fail">Show a fail</button></div><div class="roll-stage" aria-live="polite"><div class="visual-die" id="save-die">d20</div><strong id="save-result">Ready</strong><p id="save-explain">Success means you meet or beat the DC. The exact effect of success depends on the ability, spell, trap, or monster feature.</p></div></section>`
  : id==="combat" ? `<section class="interactive-lab"><h2>Live attack → damage</h2><p>First the d20 decides whether the attack hits. Only then do we roll the weapon's damage.</p><div class="roll-controls"><label>Attack bonus<input id="attack-mod" type="number" value="5"></label><label>Target AC<input id="target-ac" type="number" value="16"></label><label>Damage die<select id="damage-die"><option value="4">d4</option><option value="6">d6</option><option value="8" selected>d8</option><option value="10">d10</option><option value="12">d12</option></select></label><label>Damage mod<input id="damage-mod" type="number" value="3"></label><button class="button" id="roll-attack">Attack</button><button class="button button--ghost" id="show-hit">Show a hit</button><button class="button button--ghost" id="show-miss">Show a miss</button></div><div class="roll-stage" aria-live="polite"><div class="visual-die" id="attack-die">d20</div><strong id="attack-result">Ready</strong><p id="attack-explain">Roll d20 + attack bonus vs AC.</p></div></section>` : "";
  return shell(`<section class="page-hero"><p class="eyebrow">${topic.eyebrow}</p><h1>${topic.title}</h1><p>${topic.intro}</p></section>${interactive}<section class="section"><div class="${damage?"damage-grid":"lesson-grid"}">${damage||chunks}</div></section><section class="section section--dark"><header><p class="eyebrow">Keep learning</p><h2>Every page connects forward.</h2><p>Quick answer → deeper rule → video → interactive practice → Hearthford example → Iron Pit lab when applicable.</p></header></section>`);
};

export const systemsView = () => shell(`<section class="page-hero"><p class="eyebrow">System library</p><h1>Choose how you want the table to feel.</h1><p>Heroic fantasy, tactical teamwork, collaborative drama, investigation, or personal horror.</p></section><section class="section"><div class="system-grid">${systems.map(systemCard).join("")}</div></section>`);

export const systemView = id => {
  const system = systemById(id); if (!system) return notFoundView();
  return shell(`<article class="guide"><header class="guide-hero">${icon(system.icon)}<div>${badge(system.license.status,system.license.tone)}<p class="eyebrow">${system.edition}</p><h1>${system.name}</h1><p>${system.hook}</p></div><aside><strong>GOOD FIT</strong><p>${system.fit}</p></aside></header><nav class="tabs" aria-label="Guide sections"><a href="#/system/${system.id}/player">Player fundamentals</a><a href="#/system/${system.id}/gm">So you want to GM?</a><a href="#/system/${system.id}/license">Copyright boundary</a></nav><section id="player" class="section guide-section"><header><p class="eyebrow">Player path</p><h2>Learn enough to play the first session.</h2></header>${cards(system.player)}</section><section id="gm" class="section guide-section section--dark"><header><p class="eyebrow">Game Master path</p><h2>So you want to GM ${system.name}?</h2></header>${cards(system.gm)}</section><section id="license" class="section legal-panel"><header><p class="eyebrow">Publishing boundary</p><h2>Use what is licensed. Create the rest.</h2><p>${system.license.basis}</p></header><div class="legal-grid"><article><h3>Attribution or disclaimer</h3><p>${system.license.attribution}</p></article><article><h3>Do not copy</h3><ul>${system.license.avoid.map(item=>`<li>${item}</li>`).join("")}</ul></article></div><h3>Official sources</h3>${sources(system.sources)}<p class="review-date">Last reviewed: ${system.lastReviewed}. Practical publishing guidance, not legal advice.</p></section></article>`);
};

export const blogView = () => shell(`<section class="page-hero"><p class="eyebrow">Field notes</p><h1>Learn the hobby one useful decision at a time.</h1></section><section class="section"><div class="post-grid">${posts.map(post=>`<article><time>${post.date}</time><h2>${post.title}</h2><p>${post.dek}</p><a href="#/blog/${post.id}">Read article →</a></article>`).join("")}</div></section>`);
export const postView = id => { const post=postById(id); if(!post)return notFoundView(); return shell(`<article class="article"><a href="#/blog">← All articles</a><p class="eyebrow">${post.date}</p><h1>${post.title}</h1><p class="lede">${post.dek}</p>${post.body.map(text=>`<p>${text}</p>`).join("")}</article>`); };

export const communityView = filters => {
  const matching=listings.filter(item=>(filters.system==="all"||item.system===filters.system)&&(filters.role==="all"||item.role===filters.role));
  return shell(`<section class="page-hero"><p class="eyebrow">Community preview</p><h1>Find players and GMs without publishing private contact information.</h1><p>This is a discovery prototype. Contact remains disabled until accounts, private messaging, reporting, blocking, moderation, and age protections are implemented.</p></section><section class="section"><form class="filters" id="community-filters"><label>System<select name="system"><option value="all">All systems</option>${systems.map(system=>`<option value="${system.id}" ${filters.system===system.id?"selected":""}>${system.name} — ${system.edition}</option>`).join("")}</select></label><label>Seeking<select name="role"><option value="all">Players or GMs</option><option value="players" ${filters.role==="players"?"selected":""}>Players</option><option value="gm" ${filters.role==="gm"?"selected":""}>A GM</option></select></label><button class="button" type="submit">Apply filters</button></form><div class="listing-grid">${matching.length?matching.map(item=>`<article><p class="eyebrow">${item.region}</p><h2>${item.title}</h2><dl><div><dt>Format</dt><dd>${item.format}</dd></div><div><dt>Schedule</dt><dd>${item.schedule}</dd></div><div><dt>Age band</dt><dd>${item.age}</dd></div><div><dt>Accessibility</dt><dd>${item.access}</dd></div><div><dt>Safety</dt><dd>${item.safety}</dd></div></dl><p class="trust">${item.trust.map(check=>`<span>${check}</span>`).join("")}</p><button disabled>Request to join — coming later</button></article>`).join(""):"<p>No example listings match those filters.</p>"}</div></section><section class="section section--dark"><header><p class="eyebrow">Vetting model</p><h2>Badges must describe a documented check.</h2></header><div class="trust-grid">${trustLevels.map(([name,detail])=>`<article><h3>${name}</h3><p>${detail}</p></article>`).join("")}</div><p><strong>Privacy rule:</strong> ${communitySchema.rule}</p></section>`);
};

export const licensesView = () => shell(`<section class="page-hero"><p class="eyebrow">Copyright and licensing center</p><h1>Every system needs its own boundary.</h1><p>Open rules do not automatically include trademarks, settings, art, maps, logos, or trade dress.</p></section><section class="section"><div class="license-list">${systems.map(system=>`<article>${badge(system.license.status,system.license.tone)}<h2>${system.name}</h2><p><strong>${system.edition}</strong></p><p>${system.license.basis}</p><a href="#/system/${system.id}/license">Review full boundary →</a></article>`).join("")}</div></section>`);
export const notFoundView = () => shell(`<section class="page-hero"><p class="eyebrow">404</p><h1>That path is not on the map.</h1><a class="button" href="#/home">Return home</a></section>`);
