import { systems, systemById } from "./data/systems.js";
import { posts, postById } from "./data/blog.js";
import { listings, trustLevels, communitySchema } from "./data/community.js";
import { shell, icon, badge, cards, sources } from "./components.js";

const systemCard = system => `<article class="system-card system-card--${system.license.tone}">${icon(system.icon)}${badge(system.license.status,system.license.tone)}<p class="eyebrow">${system.edition}</p><h2>${system.name}</h2><p>${system.hook}</p><a href="#/system/${system.id}">Learn this system <span aria-hidden="true">→</span></a></article>`;

export const homeView = () => shell(`<section class="hero"><div><p class="eyebrow">Your first adventure starts here</p><h1>So you want to play a <em>tabletop roleplaying game?</em></h1><p class="hero-copy">Choose the experience you want. Learn the player fundamentals. Then follow the matching “So You Want to GM?” path when you are ready to run the table.</p><div class="hero-actions"><a class="button" href="#/systems">Choose a system</a><a class="button button--ghost" href="#/community">Find your table</a></div></div><aside><strong>START SMALL</strong><p>Pick one system, use pregenerated characters, and run a short published scenario before building a campaign.</p></aside></section><section class="section"><header><p class="eyebrow">Choose your system</p><h2>Different rules create different kinds of play.</h2><p>More systems are coming. Each guide is researched, edition-labeled, and separated from protected publisher material.</p></header><div class="system-grid">${systems.map(systemCard).join("")}</div></section><section class="split"><article><p class="eyebrow">Players</p><h2>Learn only what you need first.</h2><p>Character creation, core rolls, combat, powers, recovery, advancement, and table expectations.</p></article><article><p class="eyebrow">Game Masters</p><h2>Run situations, not scripts.</h2><p>Adjudication, encounter design, creatures, items, mysteries, campaigns, and safety.</p></article></section>`);

export const systemsView = () => shell(`<section class="page-hero"><p class="eyebrow">System library</p><h1>Choose how you want the table to feel.</h1><p>Heroic fantasy, tactical teamwork, collaborative drama, investigation, or personal horror.</p></section><section class="section"><div class="system-grid">${systems.map(systemCard).join("")}</div></section>`);

export const systemView = id => {
  const system = systemById(id); if (!system) return notFoundView();
  return shell(`<article class="guide"><header class="guide-hero">${icon(system.icon)}<div>${badge(system.license.status,system.license.tone)}<p class="eyebrow">${system.edition}</p><h1>${system.name}</h1><p>${system.hook}</p></div><aside><strong>GOOD FIT</strong><p>${system.fit}</p></aside></header><nav class="tabs" aria-label="Guide sections"><a href="#/system/${system.id}/player">Player fundamentals</a><a href="#/system/${system.id}/gm">So you want to GM?</a><a href="#/system/${system.id}/license">Copyright boundary</a></nav><section id="player" class="section guide-section"><header><p class="eyebrow">Player path</p><h2>Learn enough to play the first session.</h2></header>${cards(system.player)}</section><section id="gm" class="section guide-section section--dark"><header><p class="eyebrow">Game Master path</p><h2>So you want to GM ${system.name}?</h2></header>${cards(system.gm)}</section><section id="license" class="section legal-panel"><header><p class="eyebrow">Publishing boundary</p><h2>Use what is licensed. Create the rest.</h2><p>${system.license.basis}</p></header><div class="legal-grid"><article><h3>Attribution or disclaimer</h3><p>${system.license.attribution}</p></article><article><h3>Do not copy</h3><ul>${system.license.avoid.map(item=>`<li>${item}</li>`).join("")}</ul></article></div><h3>Official sources</h3>${sources(system.sources)}<p class="review-date">Last reviewed: ${system.lastReviewed}. Practical publishing guidance, not legal advice.</p></section></article>`);
};

export const blogView = () => shell(`<section class="page-hero"><p class="eyebrow">Field notes</p><h1>Learn the hobby one useful decision at a time.</h1></section><section class="section"><div class="post-grid">${posts.map(post=>`<article><time>${post.date}</time><h2>${post.title}</h2><p>${post.dek}</p><a href="#/blog/${post.id}">Read article →</a></article>`).join("")}</div></section>`);
export const postView = id => { const post=postById(id); if(!post)return notFoundView(); return shell(`<article class="article"><a href="#/blog">← All articles</a><p class="eyebrow">${post.date}</p><h1>${post.title}</h1><p class="lede">${post.dek}</p>${post.body.map(text=>`<p>${text}</p>`).join("")}</article>`); };

export const communityView = filters => {
  const matching=listings.filter(item=>(filters.system==="all"||item.system===filters.system)&&(filters.role==="all"||item.role===filters.role));
  return shell(`<section class="page-hero"><p class="eyebrow">Community preview</p><h1>Find players and GMs without publishing private contact information.</h1><p>This is a discovery prototype. Contact remains disabled until accounts, private messaging, reporting, blocking, moderation, and age protections are implemented.</p></section><section class="section"><form class="filters" id="community-filters"><label>System<select name="system"><option value="all">All systems</option>${systems.map(system=>`<option value="${system.id}" ${filters.system===system.id?"selected":""}>${system.name} — ${system.edition}</option>`).join("")}</select></label><label>Seeking<select name="role"><option value="all">Players or GMs</option><option value="players" ${filters.role==="players"?"selected":""}>Players</option><option value="gm" ${filters.role==="gm"?"selected":""}>A GM</option></select></label><button class="button" type="submit">Apply filters</button></form><div class="listing-grid">${matching.length?matching.map(item=>`<article><p class="eyebrow">${item.region}</p><h2>${item.title}</h2><dl><div><dt>Format</dt><dd>${item.format}</dd></div><div><dt>Schedule</dt><dd>${item.schedule}</dd></div><div><dt>Age band</dt><dd>${item.age}</dd></div><div><dt>Accessibility</dt><dd>${item.access}</dd></div><div><dt>Safety</dt><dd>${item.safety}</dd></div></dl><p class="trust">${item.trust.map(check=>`<span>${check}</span>`).join("")}</p><button disabled>Request to join — coming later</button></article>`).join(""):"<p>No example listings match those filters.</p>"}</div></section><section class="section section--dark"><header><p class="eyebrow">Vetting model</p><h2>Badges must describe a documented check.</h2></header><div class="trust-grid">${trustLevels.map(([name,detail])=>`<article><h3>${name}</h3><p>${detail}</p></article>`).join("")}</div><p><strong>Privacy rule:</strong> ${communitySchema.rule}</p></section>`);
};

export const licensesView = () => shell(`<section class="page-hero"><p class="eyebrow">Copyright and licensing center</p><h1>Every system needs its own boundary.</h1><p>Open rules do not automatically include trademarks, settings, art, maps, logos, or trade dress.</p></section><section class="section"><div class="license-list">${systems.map(system=>`<article>${badge(system.license.status,system.license.tone)}<h2>${system.name}</h2><p><strong>${system.edition}</strong></p><p>${system.license.basis}</p><a href="#/system/${system.id}/license">Review full boundary →</a></article>`).join("")}</div></section>`);
export const notFoundView = () => shell(`<section class="page-hero"><p class="eyebrow">404</p><h1>That path is not on the map.</h1><a class="button" href="#/home">Return home</a></section>`);
